[[use_microprofile_config]]
= Use MicroProfile Config
WildFly team;
:revnumber: {version}
:revdate: {localdate}
:toc: macro
:toclevels: 3
:toc-title: Use MicroProfile Config
:icons: font
:source-highlighter: coderay

ifdef::basebackend-html[toc::[]]
:numbered:

[[prerequisites]]
== Prerequisites

You have completed the http://jmesnil.github.io/wildfly.org//getstarted/[Get Started Guide].

[[requirements]]
== Requirements

=== Maven Dependencies

In order to use MicroProfile Config, you need to add it as as dependency in your `pom.xml`.

First, you need to add a dependency to the WildFly MicroProfile BOM in the `<dependencyManagement>` section:

[source,xml]
.pom.xml
----
    <dependencyManagement>
        <dependencies>
            ...

            <dependency>
                <groupId>org.wildfly.bom</groupId>
                <artifactId>wildfly-microprofile</artifactId>
                <version>${version.jboss.bom}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>
----

Then, you need to add a dependency to the MicroProfile Config API in the `<dependencies>` section:

[source,xml]
.pom.xml
----
    <dependencies>
        ...

        <dependency>
            <groupId>org.eclipse.microprofile.config</groupId>
            <artifactId>microprofile-config-api</artifactId>
            <scope>provided</scope>
        </dependency>

        ...
    </dependencies>
----

=== Galleon Layer

To provision WildFly with MicroProfile Config, you need to install its `microprofile-platform` Galleon layer.

Again, in the `pom.xml`, you need to add the `microprofile-platform` layer in the `<layers>` section of the `wildfly-maven-plugin` configuration:

[source,xml]
.pom.xml
----
<layers>
  ...

  <layer>microprofile-platform</layer>
</layers>
----

[[microprofile-config-api]]
== Use the MicroProfile Config API

You can now use `Eclipe MicroProfile Config` in your application.

As an example, you can update the `GettingStartedService.java` file to configure the text that displays "Hello":

[source,java]
.GettingStartedService.java
----
package org.wildfly.examples;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@ApplicationScoped
public class GettingStartedService {

    @Inject
    @ConfigProperty(name = "hello.text", defaultValue = "Hello")
    String helloText;

    public String hello(String name) {
        return String.format(helloText + " '%s'.", name);
    }
}
----

You can now uses the `hello.text` System property or the `HELLO_TEXT` environment variable to change the output of the service.

You can, for example, configure to output "Bonjour" by repackaging your application and restarting it with the `HELLO_TEXT` set to `Bonjour`

[source,bash]
----
mvn clean package
HELLO_TEXT="Bonjour" ./target/server/bin/standalone.sh
----

If you now access the application at http://localhost:8080 and use it, it will display "Bonjour, XXX".

[[references]]
=== References

* https://docs.wildfly.org[WildFly documentation]
* https://microprofile.io[Eclipse MicroProfile]